djagoprojesi/djagoprojesi/urls.py
from django.contrib import admin
from django.urls import path,include
from informations import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",views.index,name="index"),
    path("about/",views.about,name="about"),
    path("informations/",include("informations.urls")),
    path("user/",include("user.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

djagoprojesi/informations/urls.py
from venv import create
from django.contrib import admin
from django.urls import path
from . import views

app_name = "informations"

urlpatterns = [
    path('dashboard/', views.dashboard,name="dashboard"),
    path('addinfo/', views.addinfo,name="addinfo"),
    path('information/<int:id>', views.detail,name="detail"),
    path('update/<int:id>', views.updateInformation,name="update"),
    path('delete/<int:id>', views.deleteInformation,name="delete"),
    path('', views.informations,name="informations"),
    path('addmylist/<int:id>', views.addmylist,name="addmylist"),
]

djagoprojesi/user/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "user"

urlpatterns = [
    path('register/', views.register,name="register"),
    path('login/', views.loginUser,name="login"),
    path('logout/', views.logoutUser,name="logout"),
]

djagoprojesi/informations/models.py
from pyexpat import model
from django.db import models
from matplotlib.pyplot import title

import informations

# Create your models here.

class Information(models.Model):
    author = models.ForeignKey("auth.User",on_delete = models.CASCADE)
    title = models.CharField(max_length=50)
    content = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)
    information_file = models.FileField(blank=True,null=True,verbose_name="Add file")

    def __str__(self):
        return self.title

djagoprojesi/user/models.py
from django.db import models

# Create your models here.

djagoprojesi/informations/forms.py
from django import forms
from .models import Information

class InfoForm(forms.ModelForm):
    class Meta:
        model = Information
        fields = ["title","content","information_file"]

djagoprojesi/user/forms.py
from click import confirm
from django import forms


class LoginForm(forms.Form):
    username = forms.CharField(label = "Username")
    password = forms.CharField(label = "password",widget=forms.PasswordInput)
    

class RegisterForm(forms.Form):
    username = forms.CharField(max_length=50,label="Username")
    password = forms.CharField(max_length=20,label="Password",widget = forms.PasswordInput)
    confirm = forms.CharField(max_length=20,label="Confirm",widget = forms.PasswordInput)

    def clean(self):
        username = self.cleaned_data.get("username")
        password = self.cleaned_data.get("password")
        confirm = self.cleaned_data.get("confirm")

        if password and confirm and password !=confirm:
            raise forms.ValidationError("Passwords do not match")
        
        values={
            "username" : username,
            "password" : password
        }

        return values
 
    

djagoprojesi/informations/views.py
from ast import keyword
from pyexpat.errors import messages
from django.http import HttpRequest, HttpResponse
from django.shortcuts import redirect,render,HttpResponse,get_object_or_404
from matplotlib.style import context
from django.contrib.auth.decorators import login_required
#import informations
from .models import Information
from .forms import InfoForm
from django.contrib import messages
from django.db.models import Q


# Create your views here.

def informations(request):

    keyword = request.GET.get("keyword")

    if keyword:
        informations = Information.objects.filter(Q(content__contains = keyword) | Q(title__contains = keyword))
        context={
            "informations":informations
        }
        return render(request,"informations.html",context)


    informations = Information.objects.all()
    context={
        "informations":informations
    }
    return render(request,"informations.html",context)

def index(request):
    return render(request,"index.html")

def about(request):
    return render(request,"about.html")

@login_required(login_url="user:login")
def dashboard(request):
    informations = Information.objects.filter(author = request.user)
    context={
        "informations":informations
    }
    return render(request,"dashboard.html",context)

@login_required(login_url="user:login")
def addinfo(request):
    form =InfoForm(request.POST or None,request.FILES or None)

    if form.is_valid():
        information=form.save(commit=False)
        information.author = request.user
        information.save()

        messages.success(request,"Information successfully added")
        return redirect("informations:dashboard")



    return render(request,"addinfo.html",{"form":form})

def detail(request,id):
    information = get_object_or_404(Information,id=id)
    context={
        "information":information,
    }
    return render(request,"detail.html",context)

@login_required(login_url="user:login")
def updateInformation(request,id):
    information = get_object_or_404(Information,id=id)
    form = InfoForm(request.POST or None,request.FILES or None, instance=information)

    if information.author == request.user:
        if form.is_valid():
            information=form.save(commit=False)
            information.author = request.user
            information.save()

            messages.success(request,"Information successfully updated")
            return redirect("informations:dashboard")
    else:
        messages.info(request, "You are not authorized to update someone else's article.")
        return redirect("informations:dashboard")

    context={
        "form":form,
    }
    
    return render(request,"update.html",context)

@login_required(login_url="user:login")
def deleteInformation(request,id):
    information = get_object_or_404(Information,id=id)

    if information.author == request.user:
        information.delete()
        messages.success(request,"Information successfully deleted")
        return redirect("informations:dashboard")
    else:
        messages.info(request, "You are not authorized to delete someone else's article.")
        return redirect("informations:dashboard")


@login_required(login_url="user:login")
def addmylist(request):
    pass

djagoprojesi/user/views.py
from msilib.schema import RemoveIniFile
from django.shortcuts import redirect, render
from .forms import LoginForm, RegisterForm

from django.contrib.auth.models import User
from django.contrib.auth import login,authenticate,logout
from django.contrib import messages
# Create your views here.

def register(request):

    form = RegisterForm(request.POST or None)
    if form.is_valid():
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")

        newUser = User(username=username)
        newUser.set_password(password)

        newUser.save()
        login(request,newUser)
        messages.success(request,"You have successfully registered")

        return redirect("index")

    context = {
        "form":form
    }
    return render(request,"register.html",context)

def loginUser(request):
    form = LoginForm(request.POST or None)

    context = {
        "form":form
    }

    if form.is_valid():
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")

        user = authenticate(username=username,password=password)

        if user is None:
            messages.info(request,"Username or password is incorrect")
            return render(request,"login.html",context)

        messages.success(request,"Successfully logged in")
        login(request,user)
        return redirect("index")

    return render(request,"login.html",context)

def logoutUser(request):
    logout(request)
    messages.success(request,"You have successfully logged out")

    return redirect("index")

djagoprojesi/templates/about.html
{% extends 'layout.html' %}

{% block body %}

<h3>About</h3>

<p>A language learning app. No garbage or repetitive information. Just get the necessary knowledge ASAP.</p>



{% endblock body %}

djagoprojesi/templates/addinfo.html
{% extends 'layout.html' %}

{% block body %}
{% load crispy_forms_tags %}

<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Create Info</h3>
        <hr>
        <form method="post">
            {% csrf_token %}
        
            {{form|crispy}}
            <br>
            <button type="submit" class="btn btn-danger">Add Info</button>
        </form> 

    </div>
</div>

{% endblock body %}

djagoprojesi/templates/dashboard.html
{% extends 'layout.html' %}

{% block body %}

<h3>Dashboard</h3>
<hr>
<p>
    Welcome {{request.user.username}}
</p>
<a class="btn btn-danger" href="/informations/addinfo">Add</a>
<hr>

{% if informations %}

<table class="table">
    <thead>
      <tr>
        <th scope="col">id</th>
        <th scope="col">Title</th>
        <th scope="col">Author</th>
        <th scope="col">Date</th>
        <th scope="col">Update</th>
        <th scope="col">Delete</th>
      </tr>
    </thead>
    <tbody>
      
      {% for information in informations %}

    <tr>
        <th scope="row">{{information.id}}</th>
        <td><a href="/informations/detail/{{information.id}}">{{information.title}}</a></td>
        
        <td>{{information.author.username}}</td>
        <td>{{information.created_date}}</td>
        <td><a href="/informations/update/{{information.id}}" class="btn btn-danger">Update<a></td>
        <td><a href="/informations/delete/{{information.id}}" class="btn btn-danger">Delete<a></td>
    </tr>

      
      {% endfor %}

    </tbody>
  </table>


{% else %}

<div class="alert alert-danger">
    You do not have a information
</div>

{% endif %}

{% endblock body %}

djagoprojesi/templates/detail.html
{% extends 'layout.html' %}


{% block body %}

<h3>{{information.title}}</h3>
<p>by {{information.author.username}}</p>
<small>{{information.created_date}}</small>
<hr>
{% if information.information_field %}

<img class="img-fluid rounded" src="information.information_field.url">
<br><br>
{% endif %}
<br>


<p>{{information.content}}</p>

{% endblock body %}

djagoprojesi/templates/includes/navbar.html
<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd;">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'index'%}">Navbar</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor03" aria-controls="navbarColor03" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarColor03">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'index'%}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'informations:informations'%}">Informations</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'about'%}">About</a>
          </li>
        </ul>
        <form class="d-flex">
          {% csrf_token %}
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="keyword">
            <button class="btn btn-outline-primary me-md-5" type="submit">Search</button>
        </form>
        <div class="d-grid gap-2 d-md-flex justify-content-md-end">

          {% if request.user.is_authenticated %}
          
          <a href="{% url 'informations:dashboard'%}" class="btn btn-primary me-md-1" role="button">My Cards</a>
          <a href="{% url 'user:logout'%}" class="btn btn-primary" role="button">Logout</a>

                    
          {% else %}

          
          <a href="{% url 'user:login'%}" class="btn btn-primary me-md-1" role="button">Login</a>
          <a href="{% url 'user:register'%}" class="btn btn-primary" role="button">Register</a>


          {% endif %}

        </div>
      </div>
    </div>
  </nav>

djagoprojesi/templates/index.html
{% extends 'layout.html' %}

{% block body %}

{% if request.user.is_authenticated %}
    Welcome {{request.user.username}}
{% else %}

{% endif %}
<hr>
<div class="p-5 mb-4 bg-light rounded-3">
    <div class="container-fluid py-5">
      <h1 class="display-5 fw-bold">Welcome to Pazar Team</h1>
      <p class="col-md-8 fs-4">A language learning app. No garbage or repetitive information. Just get the necessary knowledge ASAP.</p>
      <button class="btn btn-primary btn-lg" type="button">Lets Start</button>
    </div>
  </div>

{% endblock body %}

djagoprojesi/templates/informations.html
{% extends 'layout.html' %}

{% block body %}
<h3>Informations</h3>
<hr>


<div class="d-flex justify-content-center mb-3">
{% if informations %}

<div class="card text-white bg-primary mb-3 vh-90 w-75 p-3 me-5">
  <div class="card-header">Header</div>
  <div class="card-body">
    <h5 class="card-title">Science</h5>
    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
  </div>
</div>

<table class="table">
    <thead>
      <tr>
        <th scope="col">id</th>
        <th scope="col">Title</th>
        <th scope="col">Author</th>
        <th scope="col">Date</th>
        <th scope="col">Content</th>
        <th scope="col">Add My List</th>
      </tr>
    </thead>
    <tbody>
      
      {% for information in informations %}

    <tr>
        <th scope="row">{{information.id}}</th>
        <td><a href="{% url 'informations:detail' information.id%}">{{information.title}}</a></td>
        <td>{{information.author.username}}</td>
        <td>{{information.created_date}}</td>
        <td>{{information.content|truncatewords:10}}</td>
        <td><a href="{% url 'informations:detail' information.id%}" class="btn btn-danger">Add<a></td>

    </tr> 
      {% endfor %}
    </tbody>
  </table>

{% else %}
<div class="alert alert-danger">
    Information not found
</div>

{% endif %}
</div>
{% endblock body %}

djagoprojesi/templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{%static 'css/bootstrap.min.css' %}"></link>
    <title>Hello, world!</title>
  </head>
  <body>
    {% include "includes/navbar.html" %}

    {% if messages %}
          {% for message in messages %}
          <div class="mt-2 alert alert-{{ message.tags }}">{{ message }}</div>
          {% endfor %}
    {% endif %}
    <div class="container mt-5">

        {% block body %}
        
        {% endblock body %}
    </div>
    <script src="{%static 'js/bootstrap.min.js' %}"></script>
  </body>
</html>

djagoprojesi/templates/login.html
{% extends 'layout.html' %}

{% block body %}
{% load crispy_forms_tags %}

<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Login</h3>
        <hr>
        <form method="post">
            {% csrf_token %}
        
            {{form|crispy}}
            <br>
            <button type="submit" class="btn btn-danger">Login</button>
        </form> 

    </div>
</div>

{% endblock body %}

djagoprojesi/templates/register.html
{% extends 'layout.html' %}

{% block body %}
{% load crispy_forms_tags %}

<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Register</h3>
        <hr>
        <form method="post">
            {% csrf_token %}
        
            {{form|crispy}}
            <br>
            <button type="submit" class="btn btn-danger">Register</button>
        </form> 

    </div>
</div>   

{% endblock body %}

djagoprojesi/templates/update.html
{% extends 'layout.html' %}

{% block body %}
{% load crispy_forms_tags %}

<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Update Info</h3>
        <hr>
        <form method="post">
            {% csrf_token %}
        
            {{form|crispy}}
            <br>
            <button type="submit" class="btn btn-danger">Update Info</button>
        </form> 

    </div>
</div>

{% endblock body %}